services:
  postgres:
    image: postgres:16-alpine
    container_name: appcompras-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: appcompras
      POSTGRES_USER: appcompras_user
      POSTGRES_PASSWORD: appcompras_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appcompras_user -d appcompras"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
