spring:
  application:
    name: appcompras-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/appcompras}
    username: ${DB_USERNAME:appcompras_user}
    password: ${DB_PASSWORD:appcompras_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  security:
    require-auth: ${APP_SECURITY_REQUIRE_AUTH:true}
    google-client-id: ${GOOGLE_CLIENT_ID:}

server:
  port: 8080
