name: Backend CD (ECS + Terraform)

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - "infra/**"
      - ".github/workflows/backend.yml"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
        name: production
        url: https://api.acortesdev.xyz

    env:
      AWS_REGION: us-east-1
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO: ${{ secrets.ECR_REPO }} # ej: appcompras-backend-prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set TAG
        run: |
          TAG="$(date +%Y%m%d-%H%M)-$(git rev-parse --short HEAD)"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Generated TAG=$TAG"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region "$AWS_REGION" \
          | docker login --username AWS --password-stdin \
          "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

      - name: Build & Push image to ECR (ARM64)
        working-directory: backend
        run: |
          IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$TAG"
          docker buildx build \
            --platform linux/arm64 \
            -t "$IMAGE_URI" \
            --push \
            .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra/envs/prod/runtime
        run: terraform init

      - name: Terraform Apply
        working-directory: infra/envs/prod/runtime
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
        run: terraform apply -auto-approve -var="backend_image_tag=${TAG}"

